baseURL = ""
languageCode = "zh-Hans"
title = "闲读杂记"

theme = "moments"

paginate = 10
paginatePath = '.'


[params]
    title = "闲读杂记"
    signature = "用心探索·记录世界"
    cover = "https://github.com/user-attachments/assets/58656571-bfa6-4653-97e2-05b5e7cf08d0"

    name = "Default User"
    avatar = "https://github.com/user-attachments/assets/9bb03d0d-3ede-4b0d-8f6b-7d7ed83e6404"